### PR TITLE
Added linux version of application

### PR DESCRIPTION
**Pull request by ALiwoto**

### CODE REVIEW

**Comment by ALiwoto** [comment]
Review Review Review
we need only dank's review

 </img>

**Comment by Dank-del** [comment]
> Review Review Review
> we need only dank's review
> 
> 

yamero

**Comment by ALiwoto** [comment]
Ehhhhh??! merging without reviewing??
isn't this unfair, onii-chan?

 </img>

**Comment by Dank-del** [comment]
> Ehhhhh??! merging without reviewing??
> isn't this unfair, onii-chan?
> 
> 

lmfao I have no idea about the linux part

**Pull request merged**
